services:

  collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: collector
    hostname: collector
    command: ["--config=/etc/otel-collector.yaml"]
    environment:
      - AWS_PROFILE=default
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
      - ~/.aws:/home/aoc/.aws
    ports:
      - "4318:4318"
      - "13133:13133"

  kafka:
    depends_on:
      - collector
    image: apache/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: '9885SFoKSzqkb5iyFJuegw'
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_METRIC_REPORTERS: 'com.riferrei.kafka.KIP714MetricReporter'
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://collector:4318/v1/metrics'
    volumes:
      - ./target/kip-714-metric-exporter-1.0.jar:/opt/kafka/libs/kip-714-metric-exporter-1.0.jar
    healthcheck:
      test: nc -z localhost 9092 || exit  -1
      interval: 5s
      retries: 10

  setup-kafka:
    depends_on:
      kafka:
        condition: service_healthy
    image: apache/kafka:3.7.0
    container_name: setup-kafka
    hostname: setup-kafka
    restart: "no"
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Enabling client metrics'
      /opt/kafka/bin/kafka-client-metrics.sh --bootstrap-server kafka:29092 \\
          --metrics org.apache.kafka.producer.,org.apache.kafka.consumer. \\
          --alter --generate-name --interval 1000

      echo 'Creating the topic'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create \\
         --topic load-test --partitions 1 --replication-factor 1
      "